AWSTemplateFormatVersion: '2010-09-09'

# Description: 説明カラムに入る内容
Description: "Code for DynamoDB"

# Paraneters: 
Parameters: 
  TableName: 
    Type: String
    Description: "Name of DynamoDB Table"


# Resources
Resources:
  DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
      # id：パーティションキー 
        - AttributeName: "id"  
          AttributeType: "N"
        # 単語
        - AttributeName: "vocabulary"  
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id"  
          KeyType: "HASH"
        - AttributeName: "vocabulary"  
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
      TableName: !Ref TableName

